### ISSUE TITLE
🐛 Bug Report - Country Search doesn't support locale changes

### ISSUE THREAD

**Issue by DougsSc** [typesnippet/antd-phone-input#110]
### Bug description

When changing the locale, the country search does't work according to the language.

### Code example

```
<ConfigProvider locale={locale('ptBR')}>
      <PhoneInput
        enableSearch
        onChange={onChange}
      />
</ConfigProvider>
```

### Reproduction

[_No response_](https://github.com/user-attachments/assets/dcf6f218-8d14-4f72-ae00-de16415452f6)

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

**Comment by ArtyomVancyan** [comment]
@DougsSc, thanks for reporting the issue. It is fixed in the latest release.
