### ISSUE TITLE
🪄 Enhancement - Can antd-phone-input work with react-hook-form?

### ISSUE THREAD

**Issue by giangtran8396** [typesnippet/antd-phone-input#112]
### Summary

Hi team,
I try to using antd-phone-input with react-hook-form.
It's not fill data into component
do you have any solution for this one?
and my code like below
```
useEffect(() => {
   reset({ ...formData } as object);
}, [formData, reset]);
```

```
<Form.Item
      label={'Phone number'}
    >
      <Controller
        name={'phone'}
        render={({ field }) => (
                <PhoneInput
                  size="large"
                  enableSearch
                  disableParentheses
                  {...field}
                />
              )}
      />
    </Form.Item>
```
Thank a lot

**Comment by ArtyomVancyan** [comment]
Hi @giangtran8396, please refer to [this][https://github.com/typesnippet/antd-phone-input/issues/64#issuecomment-1855867861]  answer.

**Comment by giangtran8396** [comment]
Hi @ArtyomVancyan thank you. I will check right now
