### ISSUE TITLE
Trigger onChange callback on country change

### ISSUE THREAD

**Issue by solo-bog-uptech** [typesnippet/antd-phone-input#65]
### Summary

Would be great to reset  value on change country code

**Comment by ArtyomVancyan** [comment]
Hi @solo-bog-uptech, could you please clarify what you mean? What actions do you perform, and what do you expect to be happening?

**Comment by ArtyomVancyan** [comment]
Would be great if you provide more information so I could process it. Currently, closing the issue but do not hesitate to edit and reopen.

**Comment by solo-bog-uptech** [comment]
I meant when I change country onChange callback doesn't work and value in react-hook-form doesn't change.
