### ISSUE TITLE
🐛 Bug Report - Using Antd Form `setFieldValue` or `setFieldsValue` to Update Value Doesn't Work

### ISSUE THREAD

**Issue by nygmaaa** [typesnippet/antd-phone-input#68]
### Bug description

As title. Here's the reproduction link: https://stackblitz.com/edit/stackblitz-starters-wjzl1t?file=src%2FApp.tsx

### Reproduction URL

https://stackblitz.com/edit/stackblitz-starters-wjzl1t?file=src%2FApp.tsx

### Reproduction steps

1. Use antd-phone-input in Antd Form.
2. Try to update antd-phone-input value by using `setFieldValue` or `setFieldsValue`, doesn't work.

### Browsers

Chrome

### OS

Mac

**Comment by ArtyomVancyan** [comment]
@nygmaaa, first of all, thanks for the report. Currently, it is designed so that it does not handle `form` instance changes. However, big architectural changes are coming soon and I will consider and include this in the milestone as well.

**Comment by nygmaaa** [comment]
Thanks for the response, looking forward to the new changes, closing this issue since it's intended.

**Comment by teamco** [comment]
Any progress?

**Comment by ArtyomVancyan** [comment]
@teamco, I could not find a way to implement it yet, but as the feature is getting so needed, I'll try again.

**Comment by ArtyomVancyan** [comment]
@nygmaaa, @teamco, glad to inform you that the new [release]() fixes the issue with the `setFieldValue`. Please upgrade the versions of your packages and enjoy.
