### ISSUE TITLE
💡 Feature Request - Arrow icon after the country flag

### ISSUE THREAD

**Issue by debotos** [typesnippet/antd-phone-input#88]
### Summary

An arrow icon after the country icon(dropdown trigger) to indicate it's a select/dropdown.

### Basic Example

<img width="105" alt="Screenshot 2024-05-09 at 9 44 04 AM" src="https://github.com/typesnippet/antd-phone-input/assets/29367677/b6b61fad-a463-42eb-ad74-04a32df11c05">

### Drawbacks

`addonBefore` size will increase a bit.

**Comment by ArtyomVancyan** [comment]
@debotos, when designing this component, `<flag> <country code> <arrow>` looked ugly to me, so I kept the `<flag> <country code>` form, but it's not a bad idea to make it appear using a boolean property. I think it is possible in the near future. Thanks for the suggestion.

**Comment by ArtyomVancyan** [comment]
Hey @debotos, the arrow has been added in the [latest release](https://github.com/typesnippet/antd-phone-input/releases/tag/v0.3.9) of the package. You can enable it using the `enableArrow` option of the component. You can also test it out in the [playground](https://playground.typesnippet.org/antd-phone-input-5.x/) server. Thanks for the suggestion.
